# rpmtoys.deps - Dependency metadata.

from collections import namedtuple
from enum import IntFlag

# These are from depinfo_s and depTypes[] in rpm/lib/rpmds.c
DepInfo = namedtuple("DepInfo", "name char nametag vertag flagtag idxtag")

deptypes = [
    DepInfo('Provides',         'P', 1047, 1113, 1112, None),
    DepInfo('Requires',         'R', 1049, 1050, 1048, None),
    DepInfo('Conflicts',        'C', 1054, 1055, 1053, None),
    DepInfo('Obsoletes',        'O', 1090, 1115, 1114, None),
    DepInfo('Supplements',      'S', 5052, 5053, 5054, None),
    DepInfo('Enhances',         'e', 5055, 5056, 5057, None),
    DepInfo('Recommends',       'r', 5046, 5047, 5048, None),
    DepInfo('Suggests',         's', 5049, 5050, 5051, None),
    DepInfo('Order',            'o', 5035, 5036, 5037, None),
    DepInfo('Trigger',          't', 1066, 1067, 1068, 1069),
    DepInfo('Filetrigger',      'f', 5069, 5071, 5072, 5070),
    DepInfo('Transfiletrigger', 'F', 5079, 5081, 5082, 5080),
    DepInfo('Oldsuggests',      '?', 1156, 1157, 1158, None),
    DepInfo('Oldenhances',      '?', 1159, 1160, 1161, None),
]

depinfo = {ident:d for d in deptypes for ident in (d.name, d.char)}
char2name = {d.char:d.name for d in deptypes if d.char != '?'}

class deptup(namedtuple("deptup", "name flags version index")):
    @property
    def is_rich(self):
        return self.name.startswith('(')

    @property
    def op(self):
        s = ''
        if self.flags & DepFlags.LESS:
            s += '<'
        if self.flags & DepFlags.GREATER:
            s += '>'
        if self.flags & DepFlags.EQUAL:
            s += '='
        return s

    def __str__(self):
        words = [self.name]
        flags = []
        if self.flags & DepFlags.SENSEMASK:
            words.append(self.op)
        if self.version:
            words.append(self.version)
        if self.flags & DepFlags.FIND_REQUIRES:
            flags.append('autoreq')
        if self.flags & DepFlags.FIND_PROVIDES:
            flags.append('autoprov')
        # TODO: CONFIG
        if flags:
            words.append('['+','.join(flags)+']')
        return ' '.join(words)

# TODO: parse/split rich deps

# This comes from rpmsenseFlags in rpm/lib/rpmds.h
class DepFlags(IntFlag):
    # pylama:ignore=E221
    ANY           = 0
    UNUSED_SERIAL = (1 << 0)  # Deprecated; old way of handling Epoch

    LESS          = (1 << 1)  # < operator
    GREATER       = (1 << 2)  # > operator
    EQUAL         = (1 << 3)  # = operator

    # bit 4 unused

    POSTTRANS     = (1 << 5)  # TODO
    PREREQ        = (1 << 6)  # TODO
    PRETRANS      = (1 << 7)  # TODO

    INTERP        = (1 << 8)  # gives the interpeter for a scriptlet

    SCRIPT_PRE    = (1 << 9)  # Requires(pre):
    SCRIPT_POST   = (1 << 10) # Requires(post):
    SCRIPT_PREUN  = (1 << 11) # Requires(preun):
    SCRIPT_POSTUN = (1 << 12) # Requires(postun):
    SCRIPT_VERIFY = (1 << 13) # Requires(verify): [TODO: check this..]

    FIND_REQUIRES = (1 << 14) # auto-generated by find-requires
    FIND_PROVIDES = (1 << 15) # auto-generated by find-provides

    TRIGGERIN     = (1 << 16) # TODO install trigger
    TRIGGERUN     = (1 << 17) # TODO uninstall trigger
    TRIGGERPOSTUN = (1 << 18) # TODO postuninstall trigger

    MISSINGOK     = (1 << 19) # TODO. Unused in F30.

    # bit 20-23 unused

    RPMLIB        = (1 << 24) # RPM internal requirements (TODO gpgkey?)
    TRIGGERPREIN  = (1 << 25) # TODO preinstall trigger

    KEYRING       = (1 << 26) # TODO. Unused in F30.

    # bit 27 unused

    CONFIG        = (1 << 28) # TODO

    # bit 29-31 unused

    SENSEMASK = UNUSED_SERIAL | LESS | GREATER | EQUAL
    TRIGGER = TRIGGERPREIN | TRIGGERIN | TRIGGERUN | TRIGGERPOSTUN
