#!/bin/sh
RPM_SRC_URL=https://github.com/rpm-software-management/rpm/raw/
VERSION="${1:-master}"

tmpdir=$(mktemp --tmpdir -d fetch-gen-tagtbl.XXXXXXXXXX)
if [ -d $tmpdir ]; then
    trap "rm -rf \"$tmpdir\"" 0
else
    echo "failed to create tmpdir??"
    exit 1
fi

curl -L -o $tmpdir/gentagtbl.sh $RPM_SRC_URL/$VERSION/lib/gentagtbl.sh \
        -o $tmpdir/rpmtag.h     $RPM_SRC_URL/$VERSION/lib/rpmtag.h

export AWK=awk; /bin/sh $tmpdir/gentagtbl.sh $tmpdir/rpmtag.h > $tmpdir/tagtbl.C
python <<__EOT__
import re, rpm
tagtbl_re = re.compile(r'^ *{ "\w+", "(\w+)", (RPMTAG_[A-Z0-9_]+), RPM_([A-Z0-9_]+)_TYPE, RPM_(\w+)_RETURN_TYPE, (\d+)')

print("# generated by fetch-gen-tagtbl")
print("tagtbl = [")
with open("$tmpdir/tagtbl.C") as fobj:
    for line in fobj:
        m = tagtbl_re.match(line)
        if m:
            name, sym, vtype, rtype, ext = m.groups()
            num = getattr(rpm, sym, 0)
            ext = bool(int(ext))
            print("  {!r},".format([name, num, vtype, rtype, bool(int(ext))]))
print("]")
__EOT__
